CREATE DATABASE ASIGNMENTJAVA3
USE ASIGNMENTJAVA3
CREATE TABLE USERS(
	userName VARCHAR(50) NOT NULL PRIMARY KEY,
	pass NVARCHAR(50) NOT NULL,
	roles NVARCHAR(50) NULL
)
CREATE TABLE STUDENT(
	maSv VARCHAR(50) NOT NULL PRIMARY KEY,
	hoTen NVARCHAR(50) NULL,
	email NVARCHAR(50) NULL,
	soDT VARCHAR(50) NULL,
	gioiTinh NVARCHAR(50) NULL,
	diaChi NVARCHAR(50) NULL,
	avatar VARBINARY(MAX) NULL

)
CREATE TABLE GRADE(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	maSv VARCHAR(50) NOT NULL UNIQUE,
	tiengAnh INT NULL,
	tinHoc INT NULL,
	GDTC INT NULL
	CONSTRAINT FK_GRADE_STUDENT FOREIGN KEY(maSv) REFERENCES dbo.STUDENT(maSv)
)

INSERT INTO dbo.USERS VALUES('GVquan555', N'1111', N'Giảng viên'),
							('DTquan999', N'22222', N'Đào tạo')
INSERT INTO dbo.STUDENT VALUES('PH9',N'Trần Thế Quân','quanttph19447@gmail.com','0971787297',N'Nam',N'Hà Nội',NULL)
INSERT INTO dbo.STUDENT VALUES('PH8',N'Trần Thị Thu','thutt@gmail.com','02454321315',N'Nữ',N'Quảng Bình',NULL)
INSERT INTO dbo.STUDENT VALUES('PH9',N'Phan Châu Giang','phanchaugiang@gmail.com','09213132',N'Nữ',N'Quảng Bình',NULL)
INSERT INTO dbo.STUDENT VALUES('PH6',N'Phan Châu Giang','phanchaugiang@gmail.com','09213132',N'Nữ',N'Quảng Bình',NULL)
INSERT INTO dbo.STUDENT VALUES('PH11',N'Phan Châu Giang','phanchaugiang@gmail.com','09213132',N'Nữ',N'Quảng Bình',NULL)
INSERT INTO dbo.STUDENT VALUES('PH15',N'Phan Châu Giang','phanchaugiang@gmail.com','09213132',N'Nữ',N'Quảng Bình',NULL)


INSERT INTO dbo.GRADE VALUES('sv1',8,7,10);
INSERT INTO dbo.GRADE VALUES('sv2',9,7,6);
INSERT INTO dbo.GRADE VALUES('PH8',5,7,6);
INSERT INTO dbo.GRADE VALUES('PH9',10,7,6);
INSERT INTO dbo.GRADE VALUES('PH11',5,5,6);
INSERT INTO dbo.GRADE VALUES('PH15',7,8,6);
INSERT INTO dbo.GRADE VALUES('sv8',5,9,6);
INSERT INTO dbo.GRADE VALUES('sv9',6,10,6);
INSERT INTO dbo.GRADE VALUES('sv10',9,8,6);
INSERT INTO dbo.GRADE VALUES('sv15',6,9,6);
INSERT INTO dbo.GRADE VALUES('sv16',3,7,6);

SELECT*FROM dbo.STUDENT
SELECT*FROM dbo.GRADE
SELECT*FROM dbo.USERS
