/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import service.GradeService;
import model.Grade;

/**
 *
 * @author buidu
 */
public class MarkDialog extends javax.swing.JDialog {

    private int studentId;
    private int lectureId;
    private int classID;
    private int subjectId;
    private GradeService gsv = new GradeService();

    public MarkDialog() {
    }

    /**
     * Creates new form MarkDialog
     */
    public MarkDialog(java.awt.Frame parent, boolean modal, int studentId, int lectureId, int classId, int subjectID) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.studentId = studentId;
        this.lectureId = lectureId;
        this.classID = classId;
        this.subjectId = subjectID;
        setResizable(false);
        Grade grade = gsv.getStudentMarkByid(studentId, lectureId, classId, subjectID);
        lblStudentName.setText(grade.getStudentName());
        lblSubjectName.setText(grade.getSubjectName());
        txtLab1.setText(String.valueOf(grade.getLab1()));
        txtLab2.setText(String.valueOf(grade.getLab2()));
        txtLab3.setText(String.valueOf(grade.getLab3()));
        txtLab4.setText(String.valueOf(grade.getLab4()));
        txtLab5.setText(String.valueOf(grade.getLab5()));
        txtLab6.setText(String.valueOf(grade.getLab6()));
        txtLab7.setText(String.valueOf(grade.getLab7()));
        txtLab8.setText(String.valueOf(grade.getLab8()));
        txtAssignment1.setText(String.valueOf(grade.getAssignment1()));
        txtAssignment2.setText(String.valueOf(grade.getAssignment2()));
        txtFinalAssignment.setText(String.valueOf(grade.getFinalAssignment()));
        setTitle("Môn "+grade.getSubjectName());
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                // Gọi phương thức của JFrame khi JDialog đóng
                // Chuyển sự kiện đóng từ JDialog về cho JFrame
                ((LectureForm) parent).onDialogClosed();
            }
        });
    }

    public void updateMark() {
        gsv.updateGrade(new Grade(this.subjectId, Double.parseDouble(txtLab1.getText()), Double.parseDouble(txtLab2.getText()), Double.parseDouble(txtLab3.getText()), Double.parseDouble(txtLab4.getText()), Double.parseDouble(txtLab5.getText()), Double.parseDouble(txtLab6.getText()), Double.parseDouble(txtLab7.getText()), Double.parseDouble(txtLab8.getText()), Double.parseDouble(txtAssignment1.getText()), Double.parseDouble(txtAssignment2.getText()), Double.parseDouble(txtFinalAssignment.getText()), this.studentId));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();
        lblSubjectName = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        txtLab1 = new javax.swing.JTextField();
        txtLab2 = new javax.swing.JTextField();
        txtLab3 = new javax.swing.JTextField();
        txtLab4 = new javax.swing.JTextField();
        txtLab5 = new javax.swing.JTextField();
        txtAssignment1 = new javax.swing.JTextField();
        txtLab6 = new javax.swing.JTextField();
        txtLab7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtLab8 = new javax.swing.JTextField();
        txtAssignment2 = new javax.swing.JTextField();
        txtFinalAssignment = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Lab 1");

        jLabel2.setText("Lab 4 :");

        jLabel3.setText("Lab 8:");

        jLabel4.setText("Lab 6 :");

        jLabel5.setText("Lab 3 :");

        jLabel6.setText("Lab 5 :");

        jLabel7.setText("Lab 7 :");

        jLabel8.setText("Lab 2 :");

        lblStudentName.setText("Tên sinh viên");

        lblSubjectName.setText("Môn học");

        btnSubmit.setText("Xác nhận điểm");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        txtLab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLab1ActionPerformed(evt);
            }
        });

        txtLab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLab2ActionPerformed(evt);
            }
        });

        txtLab3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLab3ActionPerformed(evt);
            }
        });

        txtLab4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLab4ActionPerformed(evt);
            }
        });

        txtLab5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLab5ActionPerformed(evt);
            }
        });

        txtAssignment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAssignment1ActionPerformed(evt);
            }
        });

        txtLab6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLab6ActionPerformed(evt);
            }
        });

        txtLab7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLab7ActionPerformed(evt);
            }
        });

        jLabel11.setText("Assignment 1");

        jLabel12.setText("Assignment 2");

        jLabel13.setText("Bài bảo vệ");

        txtLab8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLab8ActionPerformed(evt);
            }
        });

        txtAssignment2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAssignment2ActionPerformed(evt);
            }
        });

        txtFinalAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFinalAssignmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLab2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLab1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLab3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLab4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLab5, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLab6, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLab7, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLab8, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAssignment1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAssignment2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFinalAssignment, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(lblStudentName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLab1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAssignment1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLab2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAssignment2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLab3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFinalAssignment, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLab4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLab5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLab6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLab7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLab8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLab5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLab5ActionPerformed
        try {
            double lab1 = Double.parseDouble(txtLab1.getText());
            double lab2 = Double.parseDouble(txtLab2.getText());
            double lab3 = Double.parseDouble(txtLab3.getText());
            double lab4 = Double.parseDouble(txtLab4.getText());
            double lab5 = Double.parseDouble(txtLab5.getText());
            double lab6 = Double.parseDouble(txtLab6.getText());
            double lab7 = Double.parseDouble(txtLab7.getText());
            double lab8 = Double.parseDouble(txtLab8.getText());
            double assignment1 = Double.parseDouble(txtAssignment1.getText());
            double assignment2 = Double.parseDouble(txtAssignment2.getText());
            double finalAssignment = Double.parseDouble(txtFinalAssignment.getText());
            if (lab1 >= 0 && lab1 <= 10
                    && lab2 >= 0 && lab2 <= 10
                    && lab3 >= 0 && lab3 <= 10
                    && lab4 >= 0 && lab4 <= 10
                    && lab5 >= 0 && lab5 <= 10
                    && lab6 >= 0 && lab6 <= 10
                    && lab7 >= 0 && lab7 <= 10
                    && lab8 >= 0 && lab8 <= 10
                    && assignment1 >= 0 && assignment1 <= 10
                    && assignment2 >= 0 && assignment2 <= 10
                    && finalAssignment >= 0 && finalAssignment <= 10) {
                updateMark();
                JOptionPane.showMessageDialog(this, "Nhập điểm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Điểm phải trong khoảng 0 ->10", "Cảnh báo", JOptionPane.ERROR_MESSAGE);

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui Lòng nhập số", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtLab5ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        try {
            double lab1 = Double.parseDouble(txtLab1.getText());
            double lab2 = Double.parseDouble(txtLab2.getText());
            double lab3 = Double.parseDouble(txtLab3.getText());
            double lab4 = Double.parseDouble(txtLab4.getText());
            double lab5 = Double.parseDouble(txtLab5.getText());
            double lab6 = Double.parseDouble(txtLab6.getText());
            double lab7 = Double.parseDouble(txtLab7.getText());
            double lab8 = Double.parseDouble(txtLab8.getText());
            double assignment1 = Double.parseDouble(txtAssignment1.getText());
            double assignment2 = Double.parseDouble(txtAssignment2.getText());
            double finalAssignment = Double.parseDouble(txtFinalAssignment.getText());
            if (lab1 >= 0 && lab1 <= 10
                    && lab2 >= 0 && lab2 <= 10
                    && lab3 >= 0 && lab3 <= 10
                    && lab4 >= 0 && lab4 <= 10
                    && lab5 >= 0 && lab5 <= 10
                    && lab6 >= 0 && lab6 <= 10
                    && lab7 >= 0 && lab7 <= 10
                    && lab8 >= 0 && lab8 <= 10
                    && assignment1 >= 0 && assignment1 <= 10
                    && assignment2 >= 0 && assignment2 <= 10
                    && finalAssignment >= 0 && finalAssignment <= 10) {
                updateMark();
                JOptionPane.showMessageDialog(this, "Nhập điểm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Điểm phải trong khoảng 0 ->10", "Cảnh báo", JOptionPane.ERROR_MESSAGE);

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui Lòng nhập số", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtLab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLab1ActionPerformed
        try {
            double lab1 = Double.parseDouble(txtLab1.getText());
            double lab2 = Double.parseDouble(txtLab2.getText());
            double lab3 = Double.parseDouble(txtLab3.getText());
            double lab4 = Double.parseDouble(txtLab4.getText());
            double lab5 = Double.parseDouble(txtLab5.getText());
            double lab6 = Double.parseDouble(txtLab6.getText());
            double lab7 = Double.parseDouble(txtLab7.getText());
            double lab8 = Double.parseDouble(txtLab8.getText());
            double assignment1 = Double.parseDouble(txtAssignment1.getText());
            double assignment2 = Double.parseDouble(txtAssignment2.getText());
            double finalAssignment = Double.parseDouble(txtFinalAssignment.getText());
            if (lab1 >= 0 && lab1 <= 10
                    && lab2 >= 0 && lab2 <= 10
                    && lab3 >= 0 && lab3 <= 10
                    && lab4 >= 0 && lab4 <= 10
                    && lab5 >= 0 && lab5 <= 10
                    && lab6 >= 0 && lab6 <= 10
                    && lab7 >= 0 && lab7 <= 10
                    && lab8 >= 0 && lab8 <= 10
                    && assignment1 >= 0 && assignment1 <= 10
                    && assignment2 >= 0 && assignment2 <= 10
                    && finalAssignment >= 0 && finalAssignment <= 10) {
                updateMark();
                JOptionPane.showMessageDialog(this, "Nhập điểm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Điểm phải trong khoảng 0 ->10", "Cảnh báo", JOptionPane.ERROR_MESSAGE);

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui Lòng nhập số", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtLab1ActionPerformed

    private void txtLab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLab2ActionPerformed
               try {
            double lab1 = Double.parseDouble(txtLab1.getText());
            double lab2 = Double.parseDouble(txtLab2.getText());
            double lab3 = Double.parseDouble(txtLab3.getText());
            double lab4 = Double.parseDouble(txtLab4.getText());
            double lab5 = Double.parseDouble(txtLab5.getText());
            double lab6 = Double.parseDouble(txtLab6.getText());
            double lab7 = Double.parseDouble(txtLab7.getText());
            double lab8 = Double.parseDouble(txtLab8.getText());
            double assignment1 = Double.parseDouble(txtAssignment1.getText());
            double assignment2 = Double.parseDouble(txtAssignment2.getText());
            double finalAssignment = Double.parseDouble(txtFinalAssignment.getText());
            if (lab1 >= 0 && lab1 <= 10
                    && lab2 >= 0 && lab2 <= 10
                    && lab3 >= 0 && lab3 <= 10
                    && lab4 >= 0 && lab4 <= 10
                    && lab5 >= 0 && lab5 <= 10
                    && lab6 >= 0 && lab6 <= 10
                    && lab7 >= 0 && lab7 <= 10
                    && lab8 >= 0 && lab8 <= 10
                    && assignment1 >= 0 && assignment1 <= 10
                    && assignment2 >= 0 && assignment2 <= 10
                    && finalAssignment >= 0 && finalAssignment <= 10) {
                updateMark();
                JOptionPane.showMessageDialog(this, "Nhập điểm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Điểm phải trong khoảng 0 ->10", "Cảnh báo", JOptionPane.ERROR_MESSAGE);

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui Lòng nhập số", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtLab2ActionPerformed

    private void txtLab3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLab3ActionPerformed
        try {
            double lab1 = Double.parseDouble(txtLab1.getText());
            double lab2 = Double.parseDouble(txtLab2.getText());
            double lab3 = Double.parseDouble(txtLab3.getText());
            double lab4 = Double.parseDouble(txtLab4.getText());
            double lab5 = Double.parseDouble(txtLab5.getText());
            double lab6 = Double.parseDouble(txtLab6.getText());
            double lab7 = Double.parseDouble(txtLab7.getText());
            double lab8 = Double.parseDouble(txtLab8.getText());
            double assignment1 = Double.parseDouble(txtAssignment1.getText());
            double assignment2 = Double.parseDouble(txtAssignment2.getText());
            double finalAssignment = Double.parseDouble(txtFinalAssignment.getText());
            if (lab1 >= 0 && lab1 <= 10
                    && lab2 >= 0 && lab2 <= 10
                    && lab3 >= 0 && lab3 <= 10
                    && lab4 >= 0 && lab4 <= 10
                    && lab5 >= 0 && lab5 <= 10
                    && lab6 >= 0 && lab6 <= 10
                    && lab7 >= 0 && lab7 <= 10
                    && lab8 >= 0 && lab8 <= 10
                    && assignment1 >= 0 && assignment1 <= 10
                    && assignment2 >= 0 && assignment2 <= 10
                    && finalAssignment >= 0 && finalAssignment <= 10) {
                updateMark();
                JOptionPane.showMessageDialog(this, "Nhập điểm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Điểm phải trong khoảng 0 ->10", "Cảnh báo", JOptionPane.ERROR_MESSAGE);

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui Lòng nhập số", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtLab3ActionPerformed

    private void txtLab4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLab4ActionPerformed
        try {
            double lab1 = Double.parseDouble(txtLab1.getText());
            double lab2 = Double.parseDouble(txtLab2.getText());
            double lab3 = Double.parseDouble(txtLab3.getText());
            double lab4 = Double.parseDouble(txtLab4.getText());
            double lab5 = Double.parseDouble(txtLab5.getText());
            double lab6 = Double.parseDouble(txtLab6.getText());
            double lab7 = Double.parseDouble(txtLab7.getText());
            double lab8 = Double.parseDouble(txtLab8.getText());
            double assignment1 = Double.parseDouble(txtAssignment1.getText());
            double assignment2 = Double.parseDouble(txtAssignment2.getText());
            double finalAssignment = Double.parseDouble(txtFinalAssignment.getText());
            if (lab1 >= 0 && lab1 <= 10
                    && lab2 >= 0 && lab2 <= 10
                    && lab3 >= 0 && lab3 <= 10
                    && lab4 >= 0 && lab4 <= 10
                    && lab5 >= 0 && lab5 <= 10
                    && lab6 >= 0 && lab6 <= 10
                    && lab7 >= 0 && lab7 <= 10
                    && lab8 >= 0 && lab8 <= 10
                    && assignment1 >= 0 && assignment1 <= 10
                    && assignment2 >= 0 && assignment2 <= 10
                    && finalAssignment >= 0 && finalAssignment <= 10) {
                updateMark();
                JOptionPane.showMessageDialog(this, "Nhập điểm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Điểm phải trong khoảng 0 ->10", "Cảnh báo", JOptionPane.ERROR_MESSAGE);

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui Lòng nhập số", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtLab4ActionPerformed

    private void txtLab6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLab6ActionPerformed
        try {
            double lab1 = Double.parseDouble(txtLab1.getText());
            double lab2 = Double.parseDouble(txtLab2.getText());
            double lab3 = Double.parseDouble(txtLab3.getText());
            double lab4 = Double.parseDouble(txtLab4.getText());
            double lab5 = Double.parseDouble(txtLab5.getText());
            double lab6 = Double.parseDouble(txtLab6.getText());
            double lab7 = Double.parseDouble(txtLab7.getText());
            double lab8 = Double.parseDouble(txtLab8.getText());
            double assignment1 = Double.parseDouble(txtAssignment1.getText());
            double assignment2 = Double.parseDouble(txtAssignment2.getText());
            double finalAssignment = Double.parseDouble(txtFinalAssignment.getText());
            if (lab1 >= 0 && lab1 <= 10
                    && lab2 >= 0 && lab2 <= 10
                    && lab3 >= 0 && lab3 <= 10
                    && lab4 >= 0 && lab4 <= 10
                    && lab5 >= 0 && lab5 <= 10
                    && lab6 >= 0 && lab6 <= 10
                    && lab7 >= 0 && lab7 <= 10
                    && lab8 >= 0 && lab8 <= 10
                    && assignment1 >= 0 && assignment1 <= 10
                    && assignment2 >= 0 && assignment2 <= 10
                    && finalAssignment >= 0 && finalAssignment <= 10) {
                updateMark();
                JOptionPane.showMessageDialog(this, "Nhập điểm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Điểm phải trong khoảng 0 ->10", "Cảnh báo", JOptionPane.ERROR_MESSAGE);

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui Lòng nhập số", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtLab6ActionPerformed

    private void txtLab7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLab7ActionPerformed
        try {
            double lab1 = Double.parseDouble(txtLab1.getText());
            double lab2 = Double.parseDouble(txtLab2.getText());
            double lab3 = Double.parseDouble(txtLab3.getText());
            double lab4 = Double.parseDouble(txtLab4.getText());
            double lab5 = Double.parseDouble(txtLab5.getText());
            double lab6 = Double.parseDouble(txtLab6.getText());
            double lab7 = Double.parseDouble(txtLab7.getText());
            double lab8 = Double.parseDouble(txtLab8.getText());
            double assignment1 = Double.parseDouble(txtAssignment1.getText());
            double assignment2 = Double.parseDouble(txtAssignment2.getText());
            double finalAssignment = Double.parseDouble(txtFinalAssignment.getText());
            if (lab1 >= 0 && lab1 <= 10
                    && lab2 >= 0 && lab2 <= 10
                    && lab3 >= 0 && lab3 <= 10
                    && lab4 >= 0 && lab4 <= 10
                    && lab5 >= 0 && lab5 <= 10
                    && lab6 >= 0 && lab6 <= 10
                    && lab7 >= 0 && lab7 <= 10
                    && lab8 >= 0 && lab8 <= 10
                    && assignment1 >= 0 && assignment1 <= 10
                    && assignment2 >= 0 && assignment2 <= 10
                    && finalAssignment >= 0 && finalAssignment <= 10) {
                updateMark();
                JOptionPane.showMessageDialog(this, "Nhập điểm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Điểm phải trong khoảng 0 ->10", "Cảnh báo", JOptionPane.ERROR_MESSAGE);

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui Lòng nhập số", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtLab7ActionPerformed

    private void txtLab8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLab8ActionPerformed
        try {
            double lab1 = Double.parseDouble(txtLab1.getText());
            double lab2 = Double.parseDouble(txtLab2.getText());
            double lab3 = Double.parseDouble(txtLab3.getText());
            double lab4 = Double.parseDouble(txtLab4.getText());
            double lab5 = Double.parseDouble(txtLab5.getText());
            double lab6 = Double.parseDouble(txtLab6.getText());
            double lab7 = Double.parseDouble(txtLab7.getText());
            double lab8 = Double.parseDouble(txtLab8.getText());
            double assignment1 = Double.parseDouble(txtAssignment1.getText());
            double assignment2 = Double.parseDouble(txtAssignment2.getText());
            double finalAssignment = Double.parseDouble(txtFinalAssignment.getText());
            if (lab1 >= 0 && lab1 <= 10
                    && lab2 >= 0 && lab2 <= 10
                    && lab3 >= 0 && lab3 <= 10
                    && lab4 >= 0 && lab4 <= 10
                    && lab5 >= 0 && lab5 <= 10
                    && lab6 >= 0 && lab6 <= 10
                    && lab7 >= 0 && lab7 <= 10
                    && lab8 >= 0 && lab8 <= 10
                    && assignment1 >= 0 && assignment1 <= 10
                    && assignment2 >= 0 && assignment2 <= 10
                    && finalAssignment >= 0 && finalAssignment <= 10) {
                updateMark();
                JOptionPane.showMessageDialog(this, "Nhập điểm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Điểm phải trong khoảng 0 ->10", "Cảnh báo", JOptionPane.ERROR_MESSAGE);

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui Lòng nhập số", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtLab8ActionPerformed

    private void txtAssignment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAssignment1ActionPerformed
        try {
            double lab1 = Double.parseDouble(txtLab1.getText());
            double lab2 = Double.parseDouble(txtLab2.getText());
            double lab3 = Double.parseDouble(txtLab3.getText());
            double lab4 = Double.parseDouble(txtLab4.getText());
            double lab5 = Double.parseDouble(txtLab5.getText());
            double lab6 = Double.parseDouble(txtLab6.getText());
            double lab7 = Double.parseDouble(txtLab7.getText());
            double lab8 = Double.parseDouble(txtLab8.getText());
            double assignment1 = Double.parseDouble(txtAssignment1.getText());
            double assignment2 = Double.parseDouble(txtAssignment2.getText());
            double finalAssignment = Double.parseDouble(txtFinalAssignment.getText());
            if (lab1 >= 0 && lab1 <= 10
                    && lab2 >= 0 && lab2 <= 10
                    && lab3 >= 0 && lab3 <= 10
                    && lab4 >= 0 && lab4 <= 10
                    && lab5 >= 0 && lab5 <= 10
                    && lab6 >= 0 && lab6 <= 10
                    && lab7 >= 0 && lab7 <= 10
                    && lab8 >= 0 && lab8 <= 10
                    && assignment1 >= 0 && assignment1 <= 10
                    && assignment2 >= 0 && assignment2 <= 10
                    && finalAssignment >= 0 && finalAssignment <= 10) {
                updateMark();
                JOptionPane.showMessageDialog(this, "Nhập điểm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Điểm phải trong khoảng 0 ->10", "Cảnh báo", JOptionPane.ERROR_MESSAGE);

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui Lòng nhập số", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtAssignment1ActionPerformed

    private void txtAssignment2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAssignment2ActionPerformed
        try {
            double lab1 = Double.parseDouble(txtLab1.getText());
            double lab2 = Double.parseDouble(txtLab2.getText());
            double lab3 = Double.parseDouble(txtLab3.getText());
            double lab4 = Double.parseDouble(txtLab4.getText());
            double lab5 = Double.parseDouble(txtLab5.getText());
            double lab6 = Double.parseDouble(txtLab6.getText());
            double lab7 = Double.parseDouble(txtLab7.getText());
            double lab8 = Double.parseDouble(txtLab8.getText());
            double assignment1 = Double.parseDouble(txtAssignment1.getText());
            double assignment2 = Double.parseDouble(txtAssignment2.getText());
            double finalAssignment = Double.parseDouble(txtFinalAssignment.getText());
            if (lab1 >= 0 && lab1 <= 10
                    && lab2 >= 0 && lab2 <= 10
                    && lab3 >= 0 && lab3 <= 10
                    && lab4 >= 0 && lab4 <= 10
                    && lab5 >= 0 && lab5 <= 10
                    && lab6 >= 0 && lab6 <= 10
                    && lab7 >= 0 && lab7 <= 10
                    && lab8 >= 0 && lab8 <= 10
                    && assignment1 >= 0 && assignment1 <= 10
                    && assignment2 >= 0 && assignment2 <= 10
                    && finalAssignment >= 0 && finalAssignment <= 10) {
                updateMark();
                JOptionPane.showMessageDialog(this, "Nhập điểm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Điểm phải trong khoảng 0 ->10", "Cảnh báo", JOptionPane.ERROR_MESSAGE);

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui Lòng nhập số", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtAssignment2ActionPerformed

    private void txtFinalAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFinalAssignmentActionPerformed
        try {
            double lab1 = Double.parseDouble(txtLab1.getText());
            double lab2 = Double.parseDouble(txtLab2.getText());
            double lab3 = Double.parseDouble(txtLab3.getText());
            double lab4 = Double.parseDouble(txtLab4.getText());
            double lab5 = Double.parseDouble(txtLab5.getText());
            double lab6 = Double.parseDouble(txtLab6.getText());
            double lab7 = Double.parseDouble(txtLab7.getText());
            double lab8 = Double.parseDouble(txtLab8.getText());
            double assignment1 = Double.parseDouble(txtAssignment1.getText());
            double assignment2 = Double.parseDouble(txtAssignment2.getText());
            double finalAssignment = Double.parseDouble(txtFinalAssignment.getText());
            if (lab1 >= 0 && lab1 <= 10
                    && lab2 >= 0 && lab2 <= 10
                    && lab3 >= 0 && lab3 <= 10
                    && lab4 >= 0 && lab4 <= 10
                    && lab5 >= 0 && lab5 <= 10
                    && lab6 >= 0 && lab6 <= 10
                    && lab7 >= 0 && lab7 <= 10
                    && lab8 >= 0 && lab8 <= 10
                    && assignment1 >= 0 && assignment1 <= 10
                    && assignment2 >= 0 && assignment2 <= 10
                    && finalAssignment >= 0 && finalAssignment <= 10) {
                updateMark();
                JOptionPane.showMessageDialog(this, "Nhập điểm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Điểm phải trong khoảng 0 ->10", "Cảnh báo", JOptionPane.ERROR_MESSAGE);

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui Lòng nhập số", "Cảnh báo", JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtFinalAssignmentActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblSubjectName;
    private javax.swing.JTextField txtAssignment1;
    private javax.swing.JTextField txtAssignment2;
    private javax.swing.JTextField txtFinalAssignment;
    private javax.swing.JTextField txtLab1;
    private javax.swing.JTextField txtLab2;
    private javax.swing.JTextField txtLab3;
    private javax.swing.JTextField txtLab4;
    private javax.swing.JTextField txtLab5;
    private javax.swing.JTextField txtLab6;
    private javax.swing.JTextField txtLab7;
    private javax.swing.JTextField txtLab8;
    // End of variables declaration//GEN-END:variables
}
